name: todo_cli
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/nikola-moon/CLI-project

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  uuid: ^4.5.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.26.3
